# Generated by Django 5.1.4 on 2026-06-14 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_actor_i_183206_idx',
            old_name='accounts_au_actor_i_idx',
        ),
    ]
