# Generated by Django 5.1.4 on 2026-07-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed Login'), ('LOGOUT', 'Logout'), ('TICKET_CREATE', 'Ticket Created'), ('TICKET_STATUS', 'Ticket Status Changed'), ('TICKET_ASSIGN', 'Ticket Assigned'), ('MESSAGE_ADD', 'Message Added'), ('ATTACHMENT_UPLOAD', 'File Uploaded'), ('TIME_LOG', 'Time Logged'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DEACTIVATE', 'User Deactivated'), ('COMPANY_CREATE', 'Company Created'), ('COMPANY_UPDATE', 'Company Updated'), ('API_TICKET_CREATE', 'Ticket Created via API'), ('TICKET_DELETE', 'Ticket Deleted'), ('TICKET_MERGE', 'Tickets Merged'), ('EMAIL_TICKET_CREATE', 'Ticket Created via Email')], db_index=True, max_length=50),
        ),
    ]
