# Generated by Django 5.1.4 on 2026-07-19 14:58

from django.db import migrations, models
from django.utils import timezone


def backfill_blocked_status(apps, schema_editor):
    """Users deactivated under the old free-floating is_active checkbox have
    no status classification yet. Treat them as blocked (closest existing
    equivalent) so a super user has a working Unblock action for them,
    instead of leaving them unreachable via the new UI."""
    User = apps.get_model('accounts', 'User')
    User.objects.filter(is_active=False).update(status='BLOCKED', blocked_at=timezone.now())


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='purge_at',
            field=models.DateTimeField(blank=True, help_text="When an archived user's account is permanently deleted.", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Failed Login'), ('LOGOUT', 'Logout'), ('TICKET_CREATE', 'Ticket Created'), ('TICKET_STATUS', 'Ticket Status Changed'), ('TICKET_ASSIGN', 'Ticket Assigned'), ('MESSAGE_ADD', 'Message Added'), ('ATTACHMENT_UPLOAD', 'File Uploaded'), ('TIME_LOG', 'Time Logged'), ('USER_CREATE', 'User Created'), ('USER_UPDATE', 'User Updated'), ('USER_DEACTIVATE', 'User Deactivated'), ('USER_BLOCK', 'User Blocked'), ('USER_UNBLOCK', 'User Unblocked'), ('USER_ARCHIVE', 'User Archived'), ('USER_RESTORE', 'User Restored'), ('USER_PURGE', 'User Permanently Deleted'), ('COMPANY_CREATE', 'Company Created'), ('COMPANY_UPDATE', 'Company Updated'), ('API_TICKET_CREATE', 'Ticket Created via API'), ('TICKET_DELETE', 'Ticket Deleted'), ('TICKET_MERGE', 'Tickets Merged'), ('EMAIL_TICKET_CREATE', 'Ticket Created via Email')], db_index=True, max_length=50),
        ),
        migrations.RunPython(backfill_blocked_status, noop),
    ]
