# Generated by Django 5.1.4 on 2026-06-14 14:05

import apps.tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='attachments/%Y/%m/', validators=[apps.tickets.models._validate_file_size, apps.tickets.models._validate_file_type]),
        ),
    ]
