# Generated by Django 5.1.4 on 2026-07-18 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_tickets', to='tickets.ticket'),
        ),
    ]
