# Generated by Django 5.1.4 on 2026-07-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailPollState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_received_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
